sudo: required
services:
 - docker

before_install:
  - docker build -t jonathanhutton/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jonathanhutton/react-test npm test

after_success:
  - docker build -t jonathanhutton/multi-client ./client
  - docker build -t jonathanhutton/multi-nginx ./nginx
  - docker build -t jonathanhutton/multi-server ./server
  - docker build -t jonathanhutton/multi-worker ./worker
  # Log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push them to docker hub
  - docker push jonathanhutton/multi-client
  - docker push jonathanhutton/multi-nginx
  - docker push jonathanhutton/multi-server
  - docker push jonathanhutton/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-116968117365
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY

